<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>SkillCheckSorter</AssemblyName>
    <RootNamespace>SkillCheckSorter</RootNamespace>
    <ApplicationVersion>1.0.2</ApplicationVersion>
    <AssemblyVersion>1.0.2</AssemblyVersion>
    <FileVersion>1.0.2</FileVersion>
    <Version>1.0.2</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Optimize>true</Optimize>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
